---
title: "Cross Validation"
output: github_document
---

```{r set up, include = FALSE}  
library(tidyverse)
library(modelr)
library(mgcv)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = '90%'
)

theme_set(theme_classic() + theme(legend.position = 'bottom'))

options(
  ggplot2.continous.colour = 'viridis_d',
  ggplot2.continous.fill = 'viridis_d'
)

scalr_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d

set.seed(1)
```

## Simulate data

```{r}
nonlin_df = 
  tibble(
    id = 1:100,
    x = runif(100, 0, 1),
    y = 1 - 10 * (x - .3) ^ 2 + rnorm(100, 0, .3)
  )
```

```{r}
nonlin_df %>% 
  ggplot(aes(x = x, y = y)) + 
  geom_point()
```

## Cross validation -- by hand

Get training and testing datasets

```{r}
train_df = sample_n(nonlin_df, size = 80)
test_df = anti_join(nonlin_df, train_df, by = 'id')
```

Fit three models.

```{r}
linear_model = lm(y ~ x, data = train_df)
smooth_model = gam(y ~ s(x), data = train_df)
wiggly_model = gam(y ~ s(x, k = 30), sp = 10e-6, data = train_df)
```

Can I see what i just did ...

```{r}
train_df %>% 
  gather_predictions(linear_model, smooth_model, wiggly_model) %>% 
  ggplot(aes(x = x, y = y)) +
  geom_point() +
  geom_line(aes(y = pred), color = 'red') +
  facet_grid(. ~ model)
```

```{r}
rmse(linear_model, test_df)
rmse(smooth_model, test_df)
rmse(wiggly_model, test_df)
```

